# A Neural Network in 11 lines of Python

- https://iamtrask.github.io/2015/07/12/basic-python-network/

In [12]:
## Example feed-forward for 3 layer network:

f = lambda x: 1.0/(1.0+np.exp(-x))  # sigmoid activation function
x = np.random.rand(3,1)  # random input vector of  three numbers (3x1)
h1 = f(np.dot(W1, x) + b1) # calculate first hidden layer (4x1)
h2 = f(np.dot(W2, h1) + b2) # calculate second hidden layer (4x1)
out = np.dot(W3, h2) + b3  # output the forward pass "guess", (1x1)

In [7]:
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in range(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)

In [9]:
print(syn0)
print(syn1)

[[ 4.87204037  6.07539848  2.00081337 -5.07332893]
 [ 4.98921088  5.88762928  1.79022469 -4.90388152]
 [-7.45892754 -2.4283573  -2.86419357  1.89145337]]
[[-11.54904382]
 [  8.31134347]
 [ -4.56151191]
 [ -7.03066087]]


In [ ]:
# 

In [10]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print("Output After Training:")
print(l1)
print(syn0)




Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
